# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437b41186343cb9a1566972398652295026df118ff0597158cd99eaea19194a9eaf5a8e7a8432f6c9afd587d44a87d0fffbbef886d29d7cc5fab5689cf2be7ca

test:
  secret_key_base: fb1990b37a11190db2e455e371eadebd56dfdd364834ae4d46029c491991d553712a78f16c3ee2405ba398ec0d9e6195d9dd930e655ab998cd291987acf4488c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
